language: node_js

os:
  - linux
  - osx
  - windows

cache:
  npm: false

node_js:
  - 10
  - 12
  - 14

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install googlechrome -y --ignore-checksums; fi

addons:
  chrome: stable
  firefox: latest

notifications:
  email: false
